apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-database-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: registration-database
  replicas: 1
  template:
    metadata:
      labels:
        app: registration-database
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: registration-database-configmap
            - secretRef:
                name: registration-database-secret
          name: registration-database
          image: postgres:13-alpine
