apiVersion: v1
kind: Service
metadata:
  name: registration-database-service
  namespace: default
spec:
  type: NodePort
  ports:
    - name: http
      port: 5432
      targetPort: 5432
      nodePort: 30002
  selector:
    app: registration-database
