kind: Service
apiVersion: v1
metadata:
  name: question-recommendation-database-service
  namespace: default
spec:
  type: NodePort
  ports:
    - name: http
      port: 5432
      targetPort: 5432
      nodePort: 30008
  selector:
    app: question-recommendation-database
