apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: registration
  replicas: 1
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: registration-configmap
            - secretRef:
                name: registration-secret
          name: registration
          image: localhost:5000/turingq-registration
          imagePullPolicy: IfNotPresent
      initContainers:
        - envFrom:
            - configMapRef:
                name: registration-configmap
            - secretRef:
                name: registration-secret
          name: registration-migrate-db
          image: localhost:5000/turingq-registration
          command: ['node', 'ace', 'migration:run', '--force']
