# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - turingq-question-recommendation
        depends_on:
            - question-recommendation-database
    question-recommendation-database:
        image: 'postgres:13-alpine'
        container_name: turingq-question-recommendation-database
        restart: always
        ports:
            - '${DB_PORT}:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'turingq-question-recommendation-db-data:/var/lib/postgresql/data'
            - ./db-init:/docker-entrypoint-initdb.d
        networks:
            - turingq-question-recommendation
        healthcheck:
            test: ['CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE}', '-U', '${DB_USERNAME}']
            retries: 3
            timeout: 5s
networks:
    turingq-question-recommendation:
        driver: bridge
volumes:
    turingq-question-recommendation-db-data:
