version: '3'
services:
    question-recommendation-database:
        image: 'postgres:13-alpine'
        container_name: turingq-question-recommendation-database
        restart: always
        ports:
            - '${DB_PORT}:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'turingq-question-recommendation-db-data:/var/lib/postgresql/data'
            - ./db-init:/docker-entrypoint-initdb.d
        networks:
            - turingq-messages
        healthcheck:
            test: ['CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE}', '-U', '${DB_USERNAME}']
            retries: 3
            timeout: 5s
networks:
    turingq-messages:
        driver: bridge
volumes:
    turingq-question-recommendation-db-data:
