apiVersion: v1
kind: Service
metadata:
  name: authorizer-database-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: authorizer-database
  ports:
  - name: http
    port: 5432
    targetPort: 5432
    nodePort: 30004