apiVersion: v1
kind: Service
metadata:
  name: registration-service
  namespace: default
spec:
  type: NodePort
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      nodePort: 30001
  selector:
    app: registration
