kind: Service
apiVersion: v1
metadata:
  name: subscriptions-service
  namespace: default
spec:
  type: NodePort
  ports:
    - name: http
      port: 3003
      targetPort: 3003
      nodePort: 30008
  selector:
    app: subscriptions
