apiVersion: batch/v1
kind: Job
metadata:
  name: authorizer-config-job
spec:
  template:
    spec:
      containers:
      - name: authorizer-config
        image: localhost:5000/turingq-authorizer-config
        envFrom:
        - configMapRef:
            name: authorizer-config-configmap
        - secretRef:
            name: authorizer-config-secret
      restartPolicy: OnFailure
