apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-recommendation-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: question-recommendation
  replicas: 1
  template:
    metadata:
      labels:
        app: question-recommendation
    spec:
      containers:
        - name: question-recommendation
          image: localhost:5000/turingq-question-recommendation
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: question-recommendation-configmap
          - secretRef:
              name: question-recommendation-secret
      initContainers:
        - name: question-recommendation-migrate-db
          image: localhost:5000/turingq-question-recommendation
          command: ['php', 'artisan', 'migrate']
          envFrom:
          - configMapRef:
              name: question-recommendation-configmap
          - secretRef:
              name: question-recommendation-secret
